#!/bin/bash

#CONTROL ERRORES ARGUMENTOS DE ENTRADA
	if test $# -eq 0
	then
		echo "Error: por favor indique el nombre del Directorio"
		exit 1
	fi

	if test $# -gt 1
	then
		echo "Error: el numero de argumentos es mayor que 1"
		exit 2
	fi

	
	if ! test -e $1 
	then
		echo "Error: el Directorio $1 no existe"
		exit 3
	fi
	
	if ! test -d $1 
	then
		echo "Error: el Archivo $1 no es un Directorio"
		exit 4
	fi
	
	

#FIN CONTROL ERRORES ARGUMENTOS DE ENTRADA

cp ./nc ./$1
cp ./nh ./$1